# Generated by Django 2.1.2 on 2018-10-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181027_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='genero',
            field=models.IntegerField(choices=[(1, 'Select'), (2, 'Macho'), (3, 'Hembra')]),
        ),
    ]
