# Generated by Django 2.1.2 on 2018-11-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181027_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='fecha_ingreso',
            field=models.DateField(null=True),
        ),
    ]
