# Generated by Django 2.1.2 on 2018-11-29 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_mascota_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='estado',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='genero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.IntegerField(),
        ),
    ]
